[package]
name = "mnist-ai-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
image = "0.24.5"
log = "0.4.17"
log4rs = { version = "1.2.0", features = ["rolling_file_appender", "console_appender"] }
mnist = "0.5.0"
ndarray = "0.15.6"
rand = "0.8.5"
