appenders:
  stdout:
    kind: console
  training:
    kind: rolling_file
    path: logs/std.log
    append: false
    policy:
      trigger:
        kind: size
        limit: 50 mb
      roller:
        kind: fixed_window
        pattern: logs/archive/std_{}.log
        count: 5
        base: 1

root:
  level: TRACE
  appenders:
    - stdout
    - training
