appenders:
  stdout:
    kind: console
  file:
    kind: rolling_file
    path: logs/main.log
    append: false
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 500 mb
      roller:
        kind: fixed_window
        pattern: logs/archive/training_{}.log
        count: 10
        base: 1

root:
  level: trace
  appenders:
    - file

loggers:
  console:
    level: debug
    appenders:
      - stdout